name: Expo Production

defaults:
  run:
    working-directory: apps/expo

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-submit:
    name: Build and Submit
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Remove other apps
        run: rm -rf ../apps/next-react ../apps/next-react-native ../storybook-react ../storybook-react-native

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Decrypt service_account_key.json
        env:
          SERVICE_ACCOUNT_KEY_SECRET_PASSPHRASE: ${{ secrets.SERVICE_ACCOUNT_KEY_SECRET_PASSPHRASE }}
        run: |
          cd ../../scripts
          sh ./decrypt_secret.sh
          cd ../apps/expo

      - name: Application Version Bump
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: yarn bump-application-version

      - name: Set up Expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          eas-cache: true
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Update
        working-directory: apps/expo
        run: STAGE=production eas update --branch production --message "Deploy to production"

      - name: Build on EAS
        run: STAGE=production eas build --platform all --non-interactive --no-wait --auto-submit
