name: Lint

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Node.JS 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Obtain Yarn Cache directory
              id: node-cache-dir
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache Yarn dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.node-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-node-

            - name: Install modules
              run: yarn install
              env:
                  CI: TRUE

            - name: Run ESLint
              run: ESLINT_PLUGIN_DIFF_COMMIT="origin/$GITHUB_BASE_REF..." yarn eslint --output-file eslint_report.json --format json "apps/**/*.{js,jsx,ts,tsx}" "packages/**/*.{js,jsx,ts,tsx}"
              continue-on-error: true

            - name: Annotate Code Linting Results
              uses: ataylorme/eslint-annotate-action@1.2.0
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  report-json: 'eslint_report.json'

            - name: Upload ESLint report
              uses: actions/upload-artifact@v2
              with:
                  name: eslint_report.json
                  path: eslint_report.json
